/* The following code was generated by JFlex 1.4.3 on 31/10/21, 3:41 p. m. */

/*Definir el paquete*/
package analizador3;
import java.util.ArrayList;

/**
 * This class is a scanner generated by 
 * <a href="http://www.jflex.de/">JFlex</a> 1.4.3
 * on 31/10/21, 3:41 p. m. from the specification file
 * <tt>C:/Users/smith/Desktop/Recursos/Analizador3/src/analizador3/lexer.flex</tt>
 */
class Lexer {

  /** This character denotes the end of file */
  public static final int YYEOF = -1;

  /** initial size of the lookahead buffer */
  private static final int ZZ_BUFFERSIZE = 16384;

  /** lexical states */
  public static final int YYINITIAL = 0;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = { 
     0, 0
  };

  /** 
   * Translates characters to character classes
   */
  private static final String ZZ_CMAP_PACKED = 
    "\11\0\1\6\1\6\2\0\1\6\22\0\1\17\2\0\1\25\1\0"+
    "\1\5\1\35\1\24\1\41\1\40\1\34\1\33\1\23\1\7\1\10"+
    "\1\26\12\2\1\0\1\6\1\37\1\32\1\36\2\0\4\1\1\11"+
    "\1\45\5\1\1\47\1\54\2\1\1\42\1\1\1\20\1\53\7\1"+
    "\4\0\1\3\1\0\1\21\1\52\1\51\1\1\1\14\1\1\1\43"+
    "\1\55\1\46\2\1\1\22\1\44\1\12\1\16\1\56\1\1\1\15"+
    "\1\50\1\13\6\1\147\0\1\27\160\0\1\31\u1f58\0\1\30\udf50\0"+
    "\1\4\2\0";

  /** 
   * Translates characters to character classes
   */
  private static final char [] ZZ_CMAP = zzUnpackCMap(ZZ_CMAP_PACKED);

  /** 
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\1\0\1\1\1\2\1\3\1\4\1\5\2\2\3\1"+
    "\1\6\1\7\1\10\1\11\1\12\1\13\1\14\1\15"+
    "\1\16\7\2\2\0\3\2\1\17\1\0\1\20\1\0"+
    "\1\4\1\0\4\2\1\21\2\2\1\22\3\2\1\0"+
    "\13\2\1\0\1\2\1\23\4\2\1\24\1\25\5\2"+
    "\1\26\1\0\2\2\1\27\3\2\1\30\3\2\1\0"+
    "\5\2\1\31\2\2\1\0\3\2\1\32\1\2\1\33"+
    "\1\34\1\0\3\2\1\35\1\0\1\36\2\2\1\0"+
    "\2\2\1\37\1\40\1\41";

  private static int [] zzUnpackAction() {
    int [] result = new int[119];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** 
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\57\0\136\0\215\0\57\0\274\0\353\0\u011a"+
    "\0\u0149\0\u0178\0\u01a7\0\u01d6\0\57\0\57\0\57\0\57"+
    "\0\57\0\57\0\57\0\57\0\u0205\0\u0234\0\u0263\0\u0292"+
    "\0\u02c1\0\u02f0\0\u031f\0\u0149\0\u034e\0\u037d\0\u03ac\0\u03db"+
    "\0\u0149\0\u040a\0\57\0\u0439\0\u01a7\0\u01a7\0\u0468\0\u0497"+
    "\0\u04c6\0\u04f5\0\u0524\0\u0553\0\u0582\0\u034e\0\u05b1\0\u05e0"+
    "\0\u060f\0\u063e\0\u066d\0\u069c\0\u06cb\0\u06fa\0\u0729\0\u0758"+
    "\0\u0787\0\u07b6\0\u07e5\0\u0814\0\u0843\0\u0872\0\u08a1\0\136"+
    "\0\u08d0\0\u08ff\0\u092e\0\u095d\0\136\0\136\0\u098c\0\u09bb"+
    "\0\u09ea\0\u0a19\0\u0a48\0\57\0\u0a77\0\u0aa6\0\u0ad5\0\136"+
    "\0\u0b04\0\u0b33\0\u0b62\0\136\0\u0b91\0\u0bc0\0\u0bef\0\u0c1e"+
    "\0\u0c4d\0\u0c7c\0\u0cab\0\u0cda\0\u0d09\0\57\0\u0d38\0\u0d67"+
    "\0\u0d96\0\u0dc5\0\u0df4\0\u0e23\0\136\0\u0e52\0\136\0\136"+
    "\0\u0e81\0\u0eb0\0\u0edf\0\u0f0e\0\136\0\u0f3d\0\57\0\u0f6c"+
    "\0\u0f9b\0\u0fca\0\u0ff9\0\u1028\0\57\0\136\0\136";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[119];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /** 
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\2\1\3\1\4\3\2\1\5\1\6\1\2\1\7"+
    "\5\3\1\5\1\10\2\3\1\11\1\12\1\13\1\14"+
    "\3\2\1\15\1\16\1\17\1\20\1\21\1\22\1\23"+
    "\1\24\1\25\2\3\1\26\1\3\1\27\3\3\1\30"+
    "\1\31\1\32\1\3\60\0\1\3\2\33\5\0\6\3"+
    "\1\0\3\3\1\34\16\0\15\3\2\0\1\4\5\0"+
    "\1\35\50\0\1\4\55\0\1\3\2\33\5\0\1\3"+
    "\1\36\4\3\1\0\3\3\1\34\16\0\6\3\1\37"+
    "\6\3\1\0\1\3\2\33\5\0\3\3\1\40\2\3"+
    "\1\0\3\3\1\34\16\0\15\3\1\0\1\41\7\0"+
    "\6\41\1\0\3\41\17\0\15\41\1\0\3\42\1\0"+
    "\1\42\1\0\1\42\1\0\12\42\1\0\1\43\1\42"+
    "\1\0\1\44\2\0\1\42\7\0\15\42\1\0\3\45"+
    "\5\0\12\45\17\0\15\45\26\0\1\46\31\0\1\3"+
    "\2\33\5\0\4\3\1\47\1\3\1\0\1\3\1\50"+
    "\1\3\1\34\16\0\15\3\1\0\1\3\2\33\5\0"+
    "\6\3\1\0\3\3\1\34\16\0\4\3\1\51\10\3"+
    "\1\0\1\3\2\33\5\0\3\3\1\52\2\3\1\0"+
    "\3\3\1\34\16\0\15\3\1\0\1\3\2\33\5\0"+
    "\6\3\1\0\3\3\1\34\16\0\4\3\1\53\10\3"+
    "\1\0\1\3\2\33\5\0\6\3\1\0\3\3\1\34"+
    "\16\0\4\3\1\54\10\3\1\0\1\3\2\33\5\0"+
    "\6\3\1\0\1\3\1\55\1\3\1\34\16\0\15\3"+
    "\1\0\3\33\5\0\6\33\1\0\3\33\17\0\15\33"+
    "\2\0\1\56\55\0\1\3\2\33\5\0\2\3\1\57"+
    "\3\3\1\0\3\3\1\34\16\0\15\3\1\0\1\3"+
    "\2\33\5\0\6\3\1\0\3\3\1\34\16\0\7\3"+
    "\1\60\5\3\1\0\1\3\2\33\5\0\6\3\1\0"+
    "\1\3\1\61\1\3\1\34\16\0\15\3\1\0\3\42"+
    "\1\0\1\42\1\0\1\42\1\0\12\42\1\0\1\43"+
    "\1\42\4\0\1\42\7\0\15\42\30\0\1\62\27\0"+
    "\1\3\2\33\5\0\5\3\1\63\1\0\3\3\1\34"+
    "\16\0\15\3\1\0\1\3\2\33\5\0\4\3\1\64"+
    "\1\3\1\0\3\3\1\34\16\0\15\3\1\0\1\3"+
    "\2\33\5\0\1\3\1\65\4\3\1\0\3\3\1\34"+
    "\16\0\15\3\1\0\1\3\2\33\5\0\3\3\1\66"+
    "\2\3\1\0\3\3\1\34\16\0\15\3\1\0\1\3"+
    "\2\33\5\0\1\3\1\67\4\3\1\0\3\3\1\34"+
    "\16\0\15\3\1\0\1\3\2\33\5\0\3\3\1\70"+
    "\2\3\1\0\3\3\1\34\16\0\15\3\1\0\1\3"+
    "\2\33\5\0\6\3\1\0\3\3\1\34\16\0\6\3"+
    "\1\71\6\3\1\0\1\3\2\33\5\0\3\3\1\72"+
    "\1\3\1\73\1\0\3\3\1\34\16\0\15\3\1\0"+
    "\1\3\2\33\5\0\4\3\1\74\1\3\1\0\3\3"+
    "\1\34\16\0\15\3\1\0\1\3\2\33\5\0\6\3"+
    "\1\0\2\3\1\75\1\34\16\0\15\3\31\0\1\76"+
    "\26\0\1\3\2\33\5\0\6\3\1\0\3\3\1\34"+
    "\16\0\1\3\1\77\13\3\1\0\1\3\2\33\5\0"+
    "\6\3\1\0\1\3\1\100\1\3\1\34\16\0\15\3"+
    "\1\0\1\3\2\33\5\0\6\3\1\0\3\3\1\34"+
    "\16\0\1\101\10\3\1\102\1\103\1\3\1\104\1\0"+
    "\1\3\2\33\5\0\4\3\1\105\1\3\1\0\3\3"+
    "\1\34\16\0\15\3\1\0\1\3\2\33\5\0\5\3"+
    "\1\106\1\0\3\3\1\34\16\0\15\3\1\0\1\3"+
    "\2\33\5\0\1\3\1\107\4\3\1\0\3\3\1\34"+
    "\16\0\15\3\1\0\1\3\2\33\5\0\2\3\1\110"+
    "\3\3\1\0\3\3\1\34\16\0\15\3\1\0\1\3"+
    "\2\33\5\0\4\3\1\111\1\3\1\0\3\3\1\34"+
    "\16\0\15\3\1\0\1\3\2\33\5\0\1\3\1\112"+
    "\4\3\1\0\3\3\1\34\16\0\15\3\1\0\1\3"+
    "\2\33\5\0\6\3\1\0\3\3\1\34\16\0\4\3"+
    "\1\113\10\3\1\0\1\3\2\33\5\0\6\3\1\114"+
    "\3\3\1\34\16\0\15\3\24\0\1\115\33\0\1\3"+
    "\2\33\5\0\4\3\1\116\1\3\1\0\3\3\1\34"+
    "\16\0\15\3\1\0\1\3\2\33\5\0\4\3\1\117"+
    "\1\3\1\0\3\3\1\34\16\0\15\3\1\0\1\3"+
    "\2\33\5\0\6\3\1\0\3\3\1\34\16\0\4\3"+
    "\1\120\10\3\1\0\1\3\2\33\5\0\6\3\1\0"+
    "\3\3\1\34\16\0\4\3\1\121\10\3\1\0\1\3"+
    "\2\33\5\0\6\3\1\0\1\3\1\122\1\3\1\34"+
    "\16\0\15\3\1\0\1\3\2\33\5\0\2\3\1\123"+
    "\3\3\1\0\3\3\1\34\16\0\15\3\1\0\1\3"+
    "\2\33\5\0\6\3\1\0\1\3\1\124\1\3\1\34"+
    "\16\0\15\3\1\0\1\3\2\33\5\0\5\3\1\125"+
    "\1\0\3\3\1\34\16\0\15\3\1\0\1\3\2\33"+
    "\5\0\6\3\1\0\3\3\1\34\16\0\7\3\1\126"+
    "\5\3\1\0\1\3\2\33\5\0\6\3\1\0\3\3"+
    "\1\34\16\0\10\3\1\127\4\3\1\0\2\130\2\0"+
    "\1\130\1\0\1\130\1\0\12\130\2\0\1\130\4\0"+
    "\1\130\7\0\15\130\1\0\1\3\2\33\5\0\6\3"+
    "\1\0\1\3\1\131\1\3\1\34\16\0\15\3\1\0"+
    "\1\3\2\33\5\0\5\3\1\132\1\0\3\3\1\34"+
    "\16\0\15\3\1\0\1\3\2\33\5\0\3\3\1\133"+
    "\2\3\1\0\3\3\1\34\16\0\15\3\1\0\1\3"+
    "\2\33\5\0\4\3\1\134\1\3\1\0\3\3\1\34"+
    "\16\0\15\3\1\0\1\3\2\33\5\0\4\3\1\135"+
    "\1\3\1\0\3\3\1\34\16\0\15\3\1\0\1\3"+
    "\2\33\5\0\6\3\1\136\3\3\1\34\16\0\15\3"+
    "\1\0\1\3\2\33\5\0\3\3\1\137\2\3\1\0"+
    "\3\3\1\34\16\0\15\3\1\0\1\3\2\33\5\0"+
    "\6\3\1\0\3\3\1\34\16\0\4\3\1\140\10\3"+
    "\1\0\2\130\2\0\1\130\1\0\1\130\1\0\12\130"+
    "\1\0\1\141\1\130\4\0\1\130\7\0\15\130\1\0"+
    "\1\3\2\33\5\0\6\3\1\0\3\3\1\34\16\0"+
    "\2\3\1\142\12\3\1\0\1\3\2\33\5\0\6\3"+
    "\1\0\3\3\1\34\16\0\1\3\1\143\13\3\1\0"+
    "\1\3\2\33\5\0\1\3\1\144\4\3\1\0\3\3"+
    "\1\34\16\0\15\3\1\0\1\3\2\33\5\0\6\3"+
    "\1\0\1\3\1\145\1\3\1\34\16\0\15\3\1\0"+
    "\1\3\2\33\5\0\6\3\1\0\1\3\1\146\1\3"+
    "\1\34\16\0\15\3\1\0\1\3\2\33\5\0\6\3"+
    "\1\0\3\3\1\34\16\0\6\3\1\147\6\3\1\0"+
    "\1\3\2\33\5\0\4\3\1\150\1\3\1\0\3\3"+
    "\1\34\16\0\15\3\27\0\1\151\30\0\1\3\2\33"+
    "\5\0\6\3\1\0\1\3\1\152\1\3\1\34\16\0"+
    "\15\3\1\0\1\3\2\33\5\0\4\3\1\153\1\3"+
    "\1\0\3\3\1\34\16\0\15\3\1\0\1\3\2\33"+
    "\5\0\2\3\1\154\3\3\1\0\3\3\1\34\16\0"+
    "\15\3\1\0\1\3\2\33\5\0\6\3\1\0\3\3"+
    "\1\34\16\0\6\3\1\155\6\3\30\0\1\156\27\0"+
    "\1\3\2\33\5\0\6\3\1\157\3\3\1\34\16\0"+
    "\15\3\1\0\1\3\2\33\5\0\6\3\1\0\1\3"+
    "\1\160\1\3\1\34\16\0\15\3\1\0\1\3\2\33"+
    "\5\0\4\3\1\161\1\3\1\0\3\3\1\34\16\0"+
    "\15\3\4\0\1\162\53\0\1\3\2\33\5\0\6\3"+
    "\1\0\3\3\1\34\16\0\2\3\1\163\12\3\1\0"+
    "\1\3\2\33\5\0\6\3\1\0\1\3\1\164\1\3"+
    "\1\34\16\0\15\3\24\0\1\165\33\0\1\3\2\33"+
    "\5\0\6\3\1\0\1\3\1\166\1\3\1\34\16\0"+
    "\15\3\1\0\1\3\2\33\5\0\6\3\1\0\3\3"+
    "\1\34\16\0\6\3\1\167\6\3";

  private static int [] zzUnpackTrans() {
    int [] result = new int[4183];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /* error codes */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  private static final int ZZ_NO_MATCH = 1;
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /* error messages for the codes above */
  private static final String ZZ_ERROR_MSG[] = {
    "Unkown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state <code>aState</code>
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\1\0\1\11\2\1\1\11\7\1\10\11\7\1\2\0"+
    "\4\1\1\0\1\11\1\0\1\1\1\0\13\1\1\0"+
    "\13\1\1\0\15\1\1\11\1\0\12\1\1\0\5\1"+
    "\1\11\2\1\1\0\7\1\1\0\4\1\1\0\1\11"+
    "\2\1\1\0\2\1\1\11\2\1";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[119];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** the input device */
  private java.io.Reader zzReader;

  /** the current state of the DFA */
  private int zzState;

  /** the current lexical state */
  private int zzLexicalState = YYINITIAL;

  /** this buffer contains the current text to be matched and is
      the source of the yytext() string */
  private char zzBuffer[] = new char[ZZ_BUFFERSIZE];

  /** the textposition at the last accepting state */
  private int zzMarkedPos;

  /** the current text position in the buffer */
  private int zzCurrentPos;

  /** startRead marks the beginning of the yytext() string in the buffer */
  private int zzStartRead;

  /** endRead marks the last character in the buffer, that has been read
      from input */
  private int zzEndRead;

  /** number of newlines encountered up to the start of the matched text */
  private int yyline;

  /** the number of characters up to the start of the matched text */
  private int yychar;

  /**
   * the number of characters from the last newline up to the start of the 
   * matched text
   */
  private int yycolumn;

  /** 
   * zzAtBOL == true <=> the scanner is currently at the beginning of a line
   */
  private boolean zzAtBOL = true;

  /** zzAtEOF == true <=> the scanner is at the EOF */
  private boolean zzAtEOF;

  /** denotes if the user-EOF-code has already been executed */
  private boolean zzEOFDone;

  /* user code: */

public String errlex="";
public ArrayList<Token> ts = new ArrayList<Token>();



  /**
   * Creates a new scanner
   * There is also a java.io.InputStream version of this constructor.
   *
   * @param   in  the java.io.Reader to read input from.
   */
  Lexer(java.io.Reader in) {
    this.zzReader = in;
  }

  /**
   * Creates a new scanner.
   * There is also java.io.Reader version of this constructor.
   *
   * @param   in  the java.io.Inputstream to read input from.
   */
  Lexer(java.io.InputStream in) {
    this(new java.io.InputStreamReader(in));
  }

  /** 
   * Unpacks the compressed character translation table.
   *
   * @param packed   the packed character translation table
   * @return         the unpacked character translation table
   */
  private static char [] zzUnpackCMap(String packed) {
    char [] map = new char[0x10000];
    int i = 0;  /* index in packed string  */
    int j = 0;  /* index in unpacked array */
    while (i < 144) {
      int  count = packed.charAt(i++);
      char value = packed.charAt(i++);
      do map[j++] = value; while (--count > 0);
    }
    return map;
  }


  /**
   * Refills the input buffer.
   *
   * @return      <code>false</code>, iff there was new input.
   * 
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead-zzStartRead);

      /* translate stored positions */
      zzEndRead-= zzStartRead;
      zzCurrentPos-= zzStartRead;
      zzMarkedPos-= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length) {
      /* if not: blow it up */
      char newBuffer[] = new char[zzCurrentPos*2];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
    }

    /* finally: fill the buffer with new input */
    int numRead = zzReader.read(zzBuffer, zzEndRead,
                                            zzBuffer.length-zzEndRead);

    if (numRead > 0) {
      zzEndRead+= numRead;
      return false;
    }
    // unlikely but not impossible: read 0 characters, but not at end of stream    
    if (numRead == 0) {
      int c = zzReader.read();
      if (c == -1) {
        return true;
      } else {
        zzBuffer[zzEndRead++] = (char) c;
        return false;
      }     
    }

	// numRead < 0
    return true;
  }

    
  /**
   * Closes the input stream.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true;            /* indicate end of file */
    zzEndRead = zzStartRead;  /* invalidate buffer    */

    if (zzReader != null)
      zzReader.close();
  }


  /**
   * Resets the scanner to read from a new input stream.
   * Does not close the old reader.
   *
   * All internal variables are reset, the old input stream 
   * <b>cannot</b> be reused (internal buffer is discarded and lost).
   * Lexical state is set to <tt>ZZ_INITIAL</tt>.
   *
   * @param reader   the new input stream 
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzAtBOL  = true;
    zzAtEOF  = false;
    zzEOFDone = false;
    zzEndRead = zzStartRead = 0;
    zzCurrentPos = zzMarkedPos = 0;
    yyline = yychar = yycolumn = 0;
    zzLexicalState = YYINITIAL;
  }


  /**
   * Returns the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   */
  public final String yytext() {
    return new String( zzBuffer, zzStartRead, zzMarkedPos-zzStartRead );
  }


  /**
   * Returns the character at position <tt>pos</tt> from the 
   * matched text. 
   * 
   * It is equivalent to yytext().charAt(pos), but faster
   *
   * @param pos the position of the character to fetch. 
   *            A value from 0 to yylength()-1.
   *
   * @return the character at position pos
   */
  public final char yycharat(int pos) {
    return zzBuffer[zzStartRead+pos];
  }


  /**
   * Returns the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occured while scanning.
   *
   * In a wellformed scanner (no or only correct usage of 
   * yypushback(int) and a match-all fallback rule) this method 
   * will only be called with things that "Can't Possibly Happen".
   * If this method is called, something is seriously wrong
   * (e.g. a JFlex bug producing a faulty scanner etc.).
   *
   * Usual syntax/scanner level error handling should be done
   * in error fallback rules.
   *
   * @param   errorCode  the code of the errormessage to display
   */
  private void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    }
    catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  } 


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * They will be read again by then next call of the scanning method
   *
   * @param number  the number of characters to be read again.
   *                This number must not be greater than yylength()!
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Resumes scanning until the next regular expression is matched,
   * the end of input is encountered or an I/O-Error occurs.
   *
   * @return      the next token
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  public Yytoken yylex() throws java.io.IOException {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char [] zzBufferL = zzBuffer;
    char [] zzCMapL = ZZ_CMAP;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      boolean zzR = false;
      for (zzCurrentPosL = zzStartRead; zzCurrentPosL < zzMarkedPosL;
                                                             zzCurrentPosL++) {
        switch (zzBufferL[zzCurrentPosL]) {
        case '\u000B':
        case '\u000C':
        case '\u0085':
        case '\u2028':
        case '\u2029':
          yyline++;
          yycolumn = 0;
          zzR = false;
          break;
        case '\r':
          yyline++;
          yycolumn = 0;
          zzR = true;
          break;
        case '\n':
          if (zzR)
            zzR = false;
          else {
            yyline++;
            yycolumn = 0;
          }
          break;
        default:
          zzR = false;
          yycolumn++;
        }
      }

      if (zzR) {
        // peek one character ahead if it is \n (if we have counted one line too much)
        boolean zzPeek;
        if (zzMarkedPosL < zzEndReadL)
          zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        else if (zzAtEOF)
          zzPeek = false;
        else {
          boolean eof = zzRefill();
          zzEndReadL = zzEndRead;
          zzMarkedPosL = zzMarkedPos;
          zzBufferL = zzBuffer;
          if (eof) 
            zzPeek = false;
          else 
            zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        }
        if (zzPeek) yyline--;
      }
      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;
  
      zzState = ZZ_LEXSTATE[zzLexicalState];


      zzForAction: {
        while (true) {
    
          if (zzCurrentPosL < zzEndReadL)
            zzInput = zzBufferL[zzCurrentPosL++];
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = zzBufferL[zzCurrentPosL++];
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMapL[zzInput] ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          int zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
        case 22: 
          { ts.add(new Token("Variables tipo Real",yytext()));
          }
        case 34: break;
        case 2: 
          { ts.add(new Token("Identificador ",yytext()));
          }
        case 35: break;
        case 9: 
          { ts.add(new Token("Multiplicacion ",yytext()));
          }
        case 36: break;
        case 33: 
          { ts.add(new Token("Fin condicion Mientras ",yytext()));
          }
        case 37: break;
        case 23: 
          { ts.add(new Token("Fin condicion Si ",yytext()));
          }
        case 38: break;
        case 6: 
          { ts.add(new Token("Divicion ",yytext()));
          }
        case 39: break;
        case 27: 
          { ts.add(new Token("Acciones por verdadero ",yytext()));
          }
        case 40: break;
        case 14: 
          { ts.add(new Token("parentesis izquierdo ",yytext()));
          }
        case 41: break;
        case 20: 
          { ts.add(new Token("Entrada de datos ",yytext()));
          }
        case 42: break;
        case 16: 
          { ts.add(new Token("Cadena ",yytext()));
          }
        case 43: break;
        case 15: 
          { ts.add(new Token("Variables prueba",yytext()));
          }
        case 44: break;
        case 5: 
          { ts.add(new Token("Resta ",yytext()));
          }
        case 45: break;
        case 17: 
          { ts.add(new Token("Condicion Si ",yytext()));
          }
        case 46: break;
        case 18: 
          { ts.add(new Token("Real ",yytext()));
          }
        case 47: break;
        case 1: 
          { errlex+=("\n Error Lexico, en linea : "+ (yyline+1)+" , "+(yycolumn+1)+ "caracter no valido "+yytext());
          }
        case 48: break;
        case 12: 
          { ts.add(new Token("Menor que ",yytext()));
          }
        case 49: break;
        case 10: 
          { ts.add(new Token("And logico ",yytext()));
          }
        case 50: break;
        case 30: 
          { ts.add(new Token("Inicio programa ",yytext()));
          }
        case 51: break;
        case 26: 
          { ts.add(new Token("Fin condicion para ",yytext()));
          }
        case 52: break;
        case 19: 
          { ts.add(new Token("Condicion Para",yytext()));
          }
        case 53: break;
        case 24: 
          { ts.add(new Token("Condicion final ",yytext()));
          }
        case 54: break;
        case 3: 
          { ts.add(new Token("Entero ",yytext()));
          }
        case 55: break;
        case 31: 
          { ts.add(new Token("Salida de texto ",yytext()));
          }
        case 56: break;
        case 29: 
          { ts.add(new Token("Condicion Mientras",yytext()));
          }
        case 57: break;
        case 28: 
          { ts.add(new Token("salida de datos ",yytext()));
          }
        case 58: break;
        case 21: 
          { ts.add(new Token("Acciones por falso ",yytext()));
          }
        case 59: break;
        case 11: 
          { ts.add(new Token("Mayor que ",yytext()));
          }
        case 60: break;
        case 13: 
          { ts.add(new Token("parentesis derecho ",yytext()));
          }
        case 61: break;
        case 8: 
          { ts.add(new Token("Suma ",yytext()));
          }
        case 62: break;
        case 7: 
          { ts.add(new Token("Igual ",yytext()));
          }
        case 63: break;
        case 32: 
          { ts.add(new Token("Fin Programa ",yytext()));
          }
        case 64: break;
        case 25: 
          { ts.add(new Token("Variables tipo Entero ",yytext()));
          }
        case 65: break;
        case 4: 
          { 
          }
        case 66: break;
        default: 
          if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
            zzAtEOF = true;
            return null;
          } 
          else {
            zzScanError(ZZ_NO_MATCH);
          }
      }
    }
  }


}
