/* The following code was generated by JFlex 1.4.3 on 31/10/21, 3:41 p. m. */

/*Definir el paquete*/
package analizadorProyecto;
import java.util.ArrayList;
import java_cup.runtime.*;

/**
 * This class is a scanner generated by 
 * <a href="http://www.jflex.de/">JFlex</a> 1.4.3
 * on 31/10/21, 3:41 p. m. from the specification file
 * <tt>C:/Users/smith/Documents/GitHub/compiladores/Analizador/src/analizadorProyecto/lexer.flex</tt>
 */
class Lexer implements java_cup.runtime.Scanner {

  /** This character denotes the end of file */
  public static final int YYEOF = -1;

  /** initial size of the lookahead buffer */
  private static final int ZZ_BUFFERSIZE = 16384;

  /** lexical states */
  public static final int YYINITIAL = 0;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = { 
     0, 0
  };

  /** 
   * Translates characters to character classes
   */
  private static final String ZZ_CMAP_PACKED = 
    "\11\0\1\5\1\5\2\0\1\5\22\0\1\16\1\32\1\0\1\24"+
    "\1\0\1\4\1\30\1\23\1\34\1\33\1\26\1\26\1\22\1\6"+
    "\1\7\1\25\12\2\1\0\1\35\1\31\1\27\1\31\2\0\1\44"+
    "\1\1\1\60\1\1\1\10\1\46\1\43\1\63\1\55\2\1\1\50"+
    "\1\45\1\56\1\42\1\36\1\1\1\17\1\54\1\57\6\1\4\0"+
    "\1\3\1\0\1\20\1\53\1\52\1\1\1\13\1\61\1\37\1\62"+
    "\1\47\2\1\1\21\1\40\1\11\1\15\1\41\1\1\1\14\1\51"+
    "\1\12\6\1\1\0\1\30\uff83\0";

  /** 
   * Translates characters to character classes
   */
  private static final char [] ZZ_CMAP = zzUnpackCMap(ZZ_CMAP_PACKED);

  /** 
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\1\0\1\1\1\2\1\3\1\4\1\5\4\2\1\6"+
    "\2\1\2\5\1\7\1\10\1\11\1\1\1\12\1\13"+
    "\1\14\14\2\2\0\6\2\1\15\1\0\1\16\1\4"+
    "\1\0\1\11\11\2\2\17\4\2\1\20\34\2\1\21"+
    "\2\2\1\22\1\23\11\2\1\24\7\2\1\25\7\2"+
    "\1\26\2\2\1\27\1\30\15\2\1\31\10\2\1\32"+
    "\2\2\1\33\1\34\1\35\1\36\11\2\1\37\1\40";

  private static int [] zzUnpackAction() {
    int [] result = new int[167];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** 
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\64\0\150\0\234\0\64\0\320\0\u0104\0\u0138"+
    "\0\u016c\0\u01a0\0\u01d4\0\u0208\0\u023c\0\u0270\0\64\0\u02a4"+
    "\0\64\0\u02a4\0\u02a4\0\64\0\64\0\64\0\u02d8\0\u030c"+
    "\0\u0340\0\u0374\0\u03a8\0\u03dc\0\u0410\0\u0444\0\u0478\0\u04ac"+
    "\0\u04e0\0\u0514\0\u01d4\0\u0548\0\u057c\0\u05b0\0\u05e4\0\u0618"+
    "\0\u064c\0\u0680\0\u01d4\0\u0208\0\64\0\u023c\0\u023c\0\64"+
    "\0\u06b4\0\u06e8\0\u071c\0\u0750\0\u0784\0\u07b8\0\u07ec\0\u0820"+
    "\0\u0854\0\u0888\0\u08bc\0\u08f0\0\u0924\0\u0958\0\u098c\0\u0548"+
    "\0\u09c0\0\u09f4\0\u0a28\0\u0a5c\0\u0a90\0\u0ac4\0\u0af8\0\u0b2c"+
    "\0\u0b60\0\u0b94\0\u0bc8\0\u0bfc\0\u0c30\0\u0c64\0\u0c98\0\u0ccc"+
    "\0\u0d00\0\u0d34\0\u0d68\0\u0d9c\0\u0dd0\0\u0e04\0\u0e38\0\u0e6c"+
    "\0\u0ea0\0\u0ed4\0\u0f08\0\u0f3c\0\150\0\u0f70\0\u0fa4\0\150"+
    "\0\150\0\u0fd8\0\u100c\0\u1040\0\u1074\0\u10a8\0\u10dc\0\u1110"+
    "\0\u1144\0\u1178\0\150\0\u11ac\0\u11e0\0\u1214\0\u1248\0\u127c"+
    "\0\u12b0\0\u12e4\0\64\0\u1318\0\u134c\0\u1380\0\u13b4\0\u13e8"+
    "\0\u141c\0\u1450\0\150\0\u1484\0\u14b8\0\150\0\150\0\u14ec"+
    "\0\u1520\0\u1554\0\u1588\0\u15bc\0\u15f0\0\u1624\0\u1658\0\u168c"+
    "\0\u16c0\0\u16f4\0\u1728\0\u175c\0\64\0\u1790\0\u17c4\0\u17f8"+
    "\0\u182c\0\u1860\0\u1894\0\u18c8\0\u18fc\0\150\0\u1930\0\u1964"+
    "\0\150\0\150\0\150\0\150\0\u1998\0\u19cc\0\u1a00\0\u1a34"+
    "\0\u1a68\0\u1a9c\0\u1ad0\0\u1b04\0\u1b38\0\150\0\150";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[167];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /** 
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\2\1\3\1\4\2\2\1\5\1\6\1\2\1\7"+
    "\2\3\1\10\2\3\1\2\1\11\1\3\1\12\1\13"+
    "\1\14\1\15\1\16\1\17\1\20\1\21\1\22\1\23"+
    "\1\24\1\25\1\26\1\27\1\3\1\30\1\31\3\3"+
    "\1\32\1\33\1\3\1\34\1\35\2\3\1\36\4\3"+
    "\1\37\1\40\1\41\65\0\1\3\2\42\4\0\6\3"+
    "\1\0\3\3\1\43\13\0\26\3\2\0\1\4\4\0"+
    "\1\44\56\0\1\4\62\0\1\3\2\42\4\0\1\3"+
    "\1\45\4\3\1\0\3\3\1\43\13\0\13\3\1\46"+
    "\4\3\1\47\5\3\1\0\1\3\2\42\4\0\1\3"+
    "\1\50\4\3\1\0\3\3\1\43\13\0\26\3\1\0"+
    "\1\3\2\42\4\0\3\3\1\51\2\3\1\0\3\3"+
    "\1\43\13\0\26\3\1\0\1\3\2\42\4\0\3\3"+
    "\1\52\2\3\1\0\3\3\1\43\13\0\26\3\1\0"+
    "\1\53\6\0\6\53\1\0\3\53\14\0\26\53\1\0"+
    "\4\54\1\0\1\54\1\0\12\54\1\0\1\55\1\54"+
    "\2\0\1\54\6\0\26\54\1\0\3\56\4\0\12\56"+
    "\14\0\26\56\25\0\1\57\65\0\1\60\35\0\1\3"+
    "\2\42\4\0\4\3\1\61\1\3\1\0\1\62\1\63"+
    "\1\3\1\43\13\0\6\3\1\64\17\3\1\0\1\3"+
    "\2\42\4\0\6\3\1\0\3\3\1\43\13\0\11\3"+
    "\1\65\14\3\1\0\1\3\2\42\4\0\4\3\1\61"+
    "\1\3\1\0\1\3\1\63\1\3\1\43\13\0\26\3"+
    "\1\0\1\3\2\42\4\0\6\3\1\0\3\3\1\43"+
    "\13\0\11\3\1\65\5\3\1\66\6\3\1\0\1\3"+
    "\2\42\4\0\6\3\1\0\3\3\1\43\13\0\11\3"+
    "\1\67\5\3\1\70\6\3\1\0\1\3\2\42\4\0"+
    "\1\71\2\3\1\52\2\3\1\0\3\3\1\43\13\0"+
    "\26\3\1\0\1\3\2\42\4\0\6\3\1\0\3\3"+
    "\1\43\13\0\11\3\1\72\14\3\1\0\1\3\2\42"+
    "\4\0\6\3\1\0\3\3\1\43\13\0\11\3\1\72"+
    "\5\3\1\73\6\3\1\0\1\3\2\42\4\0\6\3"+
    "\1\0\3\3\1\43\13\0\11\3\1\74\14\3\1\0"+
    "\1\3\2\42\4\0\6\3\1\0\1\3\1\75\1\3"+
    "\1\43\13\0\26\3\1\0\1\3\2\42\4\0\6\3"+
    "\1\0\1\3\1\76\1\3\1\43\13\0\6\3\1\77"+
    "\17\3\1\0\3\42\4\0\6\42\1\0\3\42\14\0"+
    "\26\42\2\0\1\100\62\0\1\3\2\42\4\0\2\3"+
    "\1\101\3\3\1\0\3\3\1\43\13\0\26\3\1\0"+
    "\1\3\2\42\4\0\6\3\1\0\3\3\1\43\13\0"+
    "\14\3\1\102\11\3\1\0\1\3\2\42\4\0\6\3"+
    "\1\0\3\3\1\43\13\0\21\3\1\103\4\3\1\0"+
    "\1\3\2\42\4\0\2\3\1\104\3\3\1\0\3\3"+
    "\1\43\13\0\26\3\1\0\1\3\2\42\4\0\6\3"+
    "\1\0\1\3\1\105\1\3\1\43\13\0\26\3\1\0"+
    "\1\3\2\42\4\0\3\3\1\106\2\3\1\0\3\3"+
    "\1\43\13\0\26\3\1\0\1\3\2\42\4\0\5\3"+
    "\1\107\1\0\3\3\1\43\13\0\26\3\1\0\1\3"+
    "\2\42\4\0\6\3\1\0\3\3\1\43\13\0\4\3"+
    "\1\110\21\3\1\0\1\3\2\42\4\0\4\3\1\111"+
    "\1\3\1\0\3\3\1\43\13\0\13\3\1\112\12\3"+
    "\1\0\1\3\2\42\4\0\6\3\1\0\1\113\2\3"+
    "\1\43\13\0\16\3\1\114\7\3\1\0\1\3\2\42"+
    "\4\0\3\3\1\115\2\3\1\0\3\3\1\43\13\0"+
    "\26\3\1\0\1\3\2\42\4\0\1\116\5\3\1\0"+
    "\3\3\1\43\13\0\26\3\1\0\1\3\2\42\4\0"+
    "\1\3\1\117\4\3\1\0\3\3\1\43\13\0\26\3"+
    "\1\0\1\3\2\42\4\0\6\3\1\0\3\3\1\43"+
    "\13\0\20\3\1\120\5\3\1\0\1\3\2\42\4\0"+
    "\1\121\5\3\1\0\3\3\1\43\13\0\26\3\1\0"+
    "\1\3\2\42\4\0\1\3\1\122\4\3\1\0\3\3"+
    "\1\43\13\0\26\3\1\0\1\3\2\42\4\0\6\3"+
    "\1\0\3\3\1\43\13\0\20\3\1\123\5\3\1\0"+
    "\1\3\2\42\4\0\1\3\1\124\4\3\1\0\3\3"+
    "\1\43\13\0\26\3\1\0\1\3\2\42\4\0\6\3"+
    "\1\0\3\3\1\43\13\0\13\3\1\125\1\126\11\3"+
    "\1\0\1\3\2\42\4\0\6\3\1\0\3\3\1\43"+
    "\13\0\13\3\1\125\12\3\1\0\1\3\2\42\4\0"+
    "\6\3\1\0\3\3\1\43\13\0\16\3\1\127\7\3"+
    "\1\0\1\3\2\42\4\0\3\3\1\130\1\3\1\131"+
    "\1\0\3\3\1\43\13\0\26\3\1\0\1\3\2\42"+
    "\4\0\4\3\1\132\1\3\1\0\3\3\1\43\13\0"+
    "\26\3\1\0\1\3\2\42\4\0\6\3\1\0\3\3"+
    "\1\43\13\0\4\3\1\133\21\3\1\0\1\3\2\42"+
    "\4\0\5\3\1\131\1\0\3\3\1\43\13\0\26\3"+
    "\1\0\1\3\2\42\4\0\6\3\1\0\2\3\1\134"+
    "\1\43\13\0\26\3\1\0\1\3\2\42\4\0\4\3"+
    "\1\135\1\3\1\0\3\3\1\43\13\0\26\3\1\0"+
    "\1\3\2\42\4\0\6\3\1\0\3\3\1\43\13\0"+
    "\1\3\1\136\24\3\1\0\1\3\2\42\4\0\6\3"+
    "\1\0\3\3\1\43\13\0\5\3\1\137\20\3\1\0"+
    "\1\3\2\42\4\0\6\3\1\0\1\3\1\140\1\3"+
    "\1\43\13\0\26\3\1\0\1\3\2\42\4\0\5\3"+
    "\1\141\1\0\3\3\1\43\13\0\26\3\1\0\1\3"+
    "\2\42\4\0\6\3\1\0\3\3\1\43\13\0\6\3"+
    "\1\140\17\3\1\0\1\3\2\42\4\0\6\3\1\0"+
    "\3\3\1\43\13\0\4\3\1\141\21\3\1\0\1\3"+
    "\2\42\4\0\1\3\1\142\4\3\1\0\3\3\1\43"+
    "\13\0\26\3\1\0\1\3\2\42\4\0\6\3\1\0"+
    "\3\3\1\43\13\0\20\3\1\143\5\3\1\0\1\3"+
    "\2\42\4\0\6\3\1\0\3\3\1\43\13\0\1\144"+
    "\1\3\1\145\1\146\3\3\1\145\6\3\1\147\7\3"+
    "\1\0\1\3\2\42\4\0\6\3\1\0\3\3\1\43"+
    "\13\0\1\150\6\3\1\151\6\3\1\152\7\3\1\0"+
    "\1\3\2\42\4\0\6\3\1\0\1\135\2\3\1\43"+
    "\13\0\26\3\1\0\1\3\2\42\4\0\5\3\1\153"+
    "\1\0\3\3\1\43\13\0\26\3\1\0\1\3\2\42"+
    "\4\0\6\3\1\0\3\3\1\43\13\0\4\3\1\153"+
    "\21\3\1\0\1\3\2\42\4\0\6\3\1\0\3\3"+
    "\1\43\13\0\1\146\1\3\1\145\1\146\7\3\1\147"+
    "\12\3\1\0\1\3\2\42\4\0\2\3\1\154\3\3"+
    "\1\0\3\3\1\43\13\0\26\3\1\0\1\3\2\42"+
    "\4\0\3\3\1\155\2\3\1\0\3\3\1\43\13\0"+
    "\26\3\1\0\1\3\2\42\4\0\6\3\1\0\3\3"+
    "\1\43\13\0\21\3\1\156\4\3\1\0\1\3\2\42"+
    "\4\0\4\3\1\157\1\3\1\0\3\3\1\43\13\0"+
    "\26\3\1\0\1\3\2\42\4\0\1\3\1\160\4\3"+
    "\1\0\3\3\1\43\13\0\26\3\1\0\1\3\2\42"+
    "\4\0\6\3\1\0\3\3\1\43\13\0\11\3\1\161"+
    "\14\3\1\0\1\3\2\42\4\0\6\3\1\0\3\3"+
    "\1\43\13\0\20\3\1\162\5\3\1\0\1\3\2\42"+
    "\4\0\6\3\1\163\3\3\1\43\13\0\26\3\1\0"+
    "\1\3\2\42\4\0\4\3\1\164\1\3\1\0\3\3"+
    "\1\43\13\0\26\3\1\0\1\3\2\42\4\0\6\3"+
    "\1\0\1\165\2\3\1\43\13\0\26\3\1\0\1\3"+
    "\2\42\4\0\2\3\1\166\3\3\1\0\3\3\1\43"+
    "\13\0\26\3\1\0\1\3\2\42\4\0\6\3\1\0"+
    "\3\3\1\43\13\0\21\3\1\167\4\3\1\0\1\3"+
    "\2\42\4\0\4\3\1\170\1\3\1\0\1\3\1\171"+
    "\1\3\1\43\13\0\26\3\1\0\1\3\2\42\4\0"+
    "\6\3\1\0\3\3\1\43\13\0\11\3\1\172\14\3"+
    "\1\0\1\3\2\42\4\0\6\3\1\0\1\3\1\171"+
    "\1\3\1\43\13\0\26\3\1\0\1\3\2\42\4\0"+
    "\6\3\1\0\3\3\1\43\13\0\11\3\1\173\14\3"+
    "\1\0\1\3\2\42\4\0\6\3\1\0\3\3\1\43"+
    "\13\0\6\3\1\174\17\3\1\0\1\3\2\42\4\0"+
    "\6\3\1\0\3\3\1\43\13\0\17\3\1\175\6\3"+
    "\1\0\1\3\2\42\4\0\6\3\1\0\3\3\1\43"+
    "\13\0\17\3\1\173\6\3\1\0\1\3\2\42\4\0"+
    "\6\3\1\0\1\3\1\176\1\3\1\43\13\0\26\3"+
    "\1\0\1\3\2\42\4\0\4\3\1\177\1\3\1\0"+
    "\3\3\1\43\13\0\26\3\1\0\1\3\2\42\4\0"+
    "\6\3\1\0\3\3\1\43\13\0\6\3\1\176\17\3"+
    "\1\0\1\3\2\42\4\0\5\3\1\200\1\0\3\3"+
    "\1\43\13\0\26\3\1\0\1\3\2\42\4\0\6\3"+
    "\1\0\3\3\1\43\13\0\14\3\1\201\11\3\1\0"+
    "\1\3\2\42\4\0\6\3\1\0\3\3\1\43\13\0"+
    "\15\3\1\202\10\3\1\0\1\3\2\42\4\0\6\3"+
    "\1\0\3\3\1\43\13\0\22\3\1\203\3\3\1\0"+
    "\1\3\2\42\4\0\6\3\1\0\1\3\1\204\1\3"+
    "\1\43\13\0\26\3\1\0\1\3\2\42\4\0\6\3"+
    "\1\0\3\3\1\43\13\0\6\3\1\205\17\3\1\0"+
    "\1\3\2\42\4\0\4\3\1\206\1\3\1\0\3\3"+
    "\1\43\13\0\26\3\1\0\1\3\2\42\4\0\6\3"+
    "\1\0\1\207\2\3\1\43\13\0\26\3\1\0\1\3"+
    "\2\42\4\0\5\3\1\210\1\0\3\3\1\43\13\0"+
    "\26\3\1\0\1\3\2\42\4\0\4\3\1\211\1\3"+
    "\1\0\3\3\1\43\13\0\26\3\1\0\1\3\2\42"+
    "\4\0\3\3\1\212\2\3\1\0\3\3\1\43\13\0"+
    "\26\3\1\0\1\3\2\42\4\0\6\3\1\0\1\213"+
    "\2\3\1\43\13\0\26\3\1\0\1\3\2\42\4\0"+
    "\1\214\5\3\1\0\3\3\1\43\13\0\26\3\1\0"+
    "\1\3\2\42\4\0\6\3\1\215\3\3\1\43\13\0"+
    "\26\3\1\0\1\3\2\42\4\0\3\3\1\216\2\3"+
    "\1\0\3\3\1\43\13\0\26\3\1\0\1\3\2\42"+
    "\4\0\6\3\1\0\3\3\1\43\13\0\11\3\1\217"+
    "\14\3\1\0\1\3\2\42\4\0\1\220\5\3\1\0"+
    "\3\3\1\43\13\0\26\3\1\0\1\3\2\42\4\0"+
    "\6\3\1\0\3\3\1\43\13\0\2\3\1\221\23\3"+
    "\1\0\1\3\2\42\4\0\6\3\1\0\3\3\1\43"+
    "\13\0\7\3\1\222\16\3\1\0\1\3\2\42\4\0"+
    "\6\3\1\0\1\3\1\223\1\3\1\43\13\0\26\3"+
    "\1\0\1\3\2\42\4\0\6\3\1\0\3\3\1\43"+
    "\13\0\6\3\1\224\17\3\1\0\1\3\2\42\4\0"+
    "\6\3\1\0\3\3\1\43\13\0\1\3\1\225\24\3"+
    "\1\0\1\3\2\42\4\0\6\3\1\0\1\3\1\226"+
    "\1\3\1\43\13\0\26\3\1\0\1\3\2\42\4\0"+
    "\1\3\1\227\4\3\1\0\3\3\1\43\13\0\26\3"+
    "\1\0\1\3\2\42\4\0\6\3\1\0\3\3\1\43"+
    "\13\0\6\3\1\226\17\3\1\0\1\3\2\42\4\0"+
    "\6\3\1\0\3\3\1\43\13\0\20\3\1\230\5\3"+
    "\1\0\1\3\2\42\4\0\6\3\1\0\3\3\1\43"+
    "\13\0\13\3\1\231\12\3\1\0\1\3\2\42\4\0"+
    "\4\3\1\232\1\3\1\0\3\3\1\43\13\0\26\3"+
    "\1\0\1\3\2\42\4\0\6\3\1\0\3\3\1\43"+
    "\13\0\16\3\1\231\7\3\1\0\1\3\2\42\4\0"+
    "\6\3\1\0\1\3\1\233\1\3\1\43\13\0\26\3"+
    "\1\0\1\3\2\42\4\0\6\3\1\0\3\3\1\43"+
    "\13\0\6\3\1\233\17\3\1\0\1\3\2\42\4\0"+
    "\6\3\1\0\3\3\1\43\13\0\13\3\1\234\12\3"+
    "\1\0\1\3\2\42\4\0\6\3\1\0\3\3\1\43"+
    "\13\0\16\3\1\234\7\3\1\0\1\3\2\42\4\0"+
    "\4\3\1\235\1\3\1\0\3\3\1\43\13\0\26\3"+
    "\1\0\1\3\2\42\4\0\2\3\1\236\3\3\1\0"+
    "\3\3\1\43\13\0\26\3\1\0\1\3\2\42\4\0"+
    "\6\3\1\0\3\3\1\43\13\0\21\3\1\237\4\3"+
    "\1\0\1\3\2\42\4\0\6\3\1\0\1\3\1\240"+
    "\1\3\1\43\13\0\26\3\1\0\1\3\2\42\4\0"+
    "\4\3\1\241\1\3\1\0\3\3\1\43\13\0\26\3"+
    "\1\0\1\3\2\42\4\0\6\3\1\0\1\242\2\3"+
    "\1\43\13\0\26\3\1\0\1\3\2\42\4\0\6\3"+
    "\1\0\3\3\1\43\13\0\2\3\1\243\23\3\1\0"+
    "\1\3\2\42\4\0\6\3\1\0\1\3\1\244\1\3"+
    "\1\43\13\0\26\3\1\0\1\3\2\42\4\0\6\3"+
    "\1\0\3\3\1\43\13\0\6\3\1\245\17\3\1\0"+
    "\1\3\2\42\4\0\6\3\1\0\1\3\1\246\1\3"+
    "\1\43\13\0\26\3\1\0\1\3\2\42\4\0\6\3"+
    "\1\0\3\3\1\43\13\0\13\3\1\247\12\3\1\0"+
    "\1\3\2\42\4\0\6\3\1\0\3\3\1\43\13\0"+
    "\16\3\1\247\7\3";

  private static int [] zzUnpackTrans() {
    int [] result = new int[7020];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /* error codes */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  private static final int ZZ_NO_MATCH = 1;
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /* error messages for the codes above */
  private static final String ZZ_ERROR_MSG[] = {
    "Unkown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state <code>aState</code>
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\1\0\1\11\2\1\1\11\11\1\1\11\1\1\1\11"+
    "\2\1\3\11\14\1\2\0\7\1\1\0\1\11\1\1"+
    "\1\0\1\11\102\1\1\11\31\1\1\11\32\1";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[167];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** the input device */
  private java.io.Reader zzReader;

  /** the current state of the DFA */
  private int zzState;

  /** the current lexical state */
  private int zzLexicalState = YYINITIAL;

  /** this buffer contains the current text to be matched and is
      the source of the yytext() string */
  private char zzBuffer[] = new char[ZZ_BUFFERSIZE];

  /** the textposition at the last accepting state */
  private int zzMarkedPos;

  /** the current text position in the buffer */
  private int zzCurrentPos;

  /** startRead marks the beginning of the yytext() string in the buffer */
  private int zzStartRead;

  /** endRead marks the last character in the buffer, that has been read
      from input */
  private int zzEndRead;

  /** number of newlines encountered up to the start of the matched text */
  private int yyline;

  /** the number of characters up to the start of the matched text */
  private int yychar;

  /**
   * the number of characters from the last newline up to the start of the 
   * matched text
   */
  private int yycolumn;

  /** 
   * zzAtBOL == true <=> the scanner is currently at the beginning of a line
   */
  private boolean zzAtBOL = true;

  /** zzAtEOF == true <=> the scanner is at the EOF */
  private boolean zzAtEOF;

  /** denotes if the user-EOF-code has already been executed */
  private boolean zzEOFDone;

  /* user code: */

public String errlex="";
public ArrayList<Token> ts = new ArrayList<Token>();
public Symbol symbol(int type){
    return new Symbol(type,yyline,yycolumn);

    }


  /**
   * Creates a new scanner
   * There is also a java.io.InputStream version of this constructor.
   *
   * @param   in  the java.io.Reader to read input from.
   */
  Lexer(java.io.Reader in) {
    this.zzReader = in;
  }

  /**
   * Creates a new scanner.
   * There is also java.io.Reader version of this constructor.
   *
   * @param   in  the java.io.Inputstream to read input from.
   */
  Lexer(java.io.InputStream in) {
    this(new java.io.InputStreamReader(in));
  }

  /** 
   * Unpacks the compressed character translation table.
   *
   * @param packed   the packed character translation table
   * @return         the unpacked character translation table
   */
  private static char [] zzUnpackCMap(String packed) {
    char [] map = new char[0x10000];
    int i = 0;  /* index in packed string  */
    int j = 0;  /* index in unpacked array */
    while (i < 150) {
      int  count = packed.charAt(i++);
      char value = packed.charAt(i++);
      do map[j++] = value; while (--count > 0);
    }
    return map;
  }


  /**
   * Refills the input buffer.
   *
   * @return      <code>false</code>, iff there was new input.
   * 
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead-zzStartRead);

      /* translate stored positions */
      zzEndRead-= zzStartRead;
      zzCurrentPos-= zzStartRead;
      zzMarkedPos-= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length) {
      /* if not: blow it up */
      char newBuffer[] = new char[zzCurrentPos*2];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
    }

    /* finally: fill the buffer with new input */
    int numRead = zzReader.read(zzBuffer, zzEndRead,
                                            zzBuffer.length-zzEndRead);

    if (numRead > 0) {
      zzEndRead+= numRead;
      return false;
    }
    // unlikely but not impossible: read 0 characters, but not at end of stream    
    if (numRead == 0) {
      int c = zzReader.read();
      if (c == -1) {
        return true;
      } else {
        zzBuffer[zzEndRead++] = (char) c;
        return false;
      }     
    }

	// numRead < 0
    return true;
  }

    
  /**
   * Closes the input stream.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true;            /* indicate end of file */
    zzEndRead = zzStartRead;  /* invalidate buffer    */

    if (zzReader != null)
      zzReader.close();
  }


  /**
   * Resets the scanner to read from a new input stream.
   * Does not close the old reader.
   *
   * All internal variables are reset, the old input stream 
   * <b>cannot</b> be reused (internal buffer is discarded and lost).
   * Lexical state is set to <tt>ZZ_INITIAL</tt>.
   *
   * @param reader   the new input stream 
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzAtBOL  = true;
    zzAtEOF  = false;
    zzEOFDone = false;
    zzEndRead = zzStartRead = 0;
    zzCurrentPos = zzMarkedPos = 0;
    yyline = yychar = yycolumn = 0;
    zzLexicalState = YYINITIAL;
  }


  /**
   * Returns the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   */
  public final String yytext() {
    return new String( zzBuffer, zzStartRead, zzMarkedPos-zzStartRead );
  }


  /**
   * Returns the character at position <tt>pos</tt> from the 
   * matched text. 
   * 
   * It is equivalent to yytext().charAt(pos), but faster
   *
   * @param pos the position of the character to fetch. 
   *            A value from 0 to yylength()-1.
   *
   * @return the character at position pos
   */
  public final char yycharat(int pos) {
    return zzBuffer[zzStartRead+pos];
  }


  /**
   * Returns the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occured while scanning.
   *
   * In a wellformed scanner (no or only correct usage of 
   * yypushback(int) and a match-all fallback rule) this method 
   * will only be called with things that "Can't Possibly Happen".
   * If this method is called, something is seriously wrong
   * (e.g. a JFlex bug producing a faulty scanner etc.).
   *
   * Usual syntax/scanner level error handling should be done
   * in error fallback rules.
   *
   * @param   errorCode  the code of the errormessage to display
   */
  private void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    }
    catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  } 


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * They will be read again by then next call of the scanning method
   *
   * @param number  the number of characters to be read again.
   *                This number must not be greater than yylength()!
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Contains user EOF-code, which will be executed exactly once,
   * when the end of file is reached
   */
  private void zzDoEOF() throws java.io.IOException {
    if (!zzEOFDone) {
      zzEOFDone = true;
      yyclose();
    }
  }


  /**
   * Resumes scanning until the next regular expression is matched,
   * the end of input is encountered or an I/O-Error occurs.
   *
   * @return      the next token
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  public java_cup.runtime.Symbol next_token() throws java.io.IOException {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char [] zzBufferL = zzBuffer;
    char [] zzCMapL = ZZ_CMAP;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      boolean zzR = false;
      for (zzCurrentPosL = zzStartRead; zzCurrentPosL < zzMarkedPosL;
                                                             zzCurrentPosL++) {
        switch (zzBufferL[zzCurrentPosL]) {
        case '\u000B':
        case '\u000C':
        case '\u0085':
        case '\u2028':
        case '\u2029':
          yyline++;
          yycolumn = 0;
          zzR = false;
          break;
        case '\r':
          yyline++;
          yycolumn = 0;
          zzR = true;
          break;
        case '\n':
          if (zzR)
            zzR = false;
          else {
            yyline++;
            yycolumn = 0;
          }
          break;
        default:
          zzR = false;
          yycolumn++;
        }
      }

      if (zzR) {
        // peek one character ahead if it is \n (if we have counted one line too much)
        boolean zzPeek;
        if (zzMarkedPosL < zzEndReadL)
          zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        else if (zzAtEOF)
          zzPeek = false;
        else {
          boolean eof = zzRefill();
          zzEndReadL = zzEndRead;
          zzMarkedPosL = zzMarkedPos;
          zzBufferL = zzBuffer;
          if (eof) 
            zzPeek = false;
          else 
            zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        }
        if (zzPeek) yyline--;
      }
      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;
  
      zzState = ZZ_LEXSTATE[zzLexicalState];


      zzForAction: {
        while (true) {
    
          if (zzCurrentPosL < zzEndReadL)
            zzInput = zzBufferL[zzCurrentPosL++];
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = zzBufferL[zzCurrentPosL++];
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMapL[zzInput] ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          int zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
        case 19: 
          { ts.add(new Token("Condicion final ",yytext()));return symbol(sym.paso);
          }
        case 33: break;
        case 9: 
          { ts.add(new Token("Op. relacional ", yytext()));return symbol(sym.or);
          }
        case 34: break;
        case 18: 
          { ts.add(new Token("Condicion Para",yytext()));return symbol(sym.para);
          }
        case 35: break;
        case 24: 
          { ts.add(new Token("Palabra reservada ", yytext()));return symbol(sym.hacer);
          }
        case 36: break;
        case 27: 
          { ts.add(new Token("Acciones por verdadero ",yytext()));return symbol(sym.enton);
          }
        case 37: break;
        case 29: 
          { ts.add(new Token("Inicio programa ",yytext()));return symbol(sym.inicio);
          }
        case 38: break;
        case 22: 
          { ts.add(new Token("Fin condicion Si ",yytext()));return symbol(sym.finsi);
          }
        case 39: break;
        case 23: 
          { ts.add(new Token("Condicion final ",yytext()));return symbol(sym.hasta);
          }
        case 40: break;
        case 5: 
          { ts.add(new Token("operador",yytext()));return symbol(sym.op);
          }
        case 41: break;
        case 10: 
          { ts.add(new Token("parentesis derecho ",yytext()));return symbol(sym.pd);
          }
        case 42: break;
        case 31: 
          { ts.add(new Token("Fin Programa ",yytext()));return symbol(sym.fin);
          }
        case 43: break;
        case 32: 
          { ts.add(new Token("Palabra reservada ", yytext()));return symbol(sym.finmien);
          }
        case 44: break;
        case 16: 
          { ts.add(new Token("Real ",yytext()));return symbol(sym.real);
          }
        case 45: break;
        case 1: 
          { errlex+=("\n Error Lexico, en linea : "+ (yyline+1)+" , "+(yycolumn+1)+ "caracter no valido "+yytext());
          }
        case 46: break;
        case 12: 
          { ts.add(new Token("Punto y coma",yytext()));return symbol(sym.p_coma);
          }
        case 47: break;
        case 26: 
          { ts.add(new Token("Fin condicion para ",yytext()));return symbol(sym.finpara);
          }
        case 48: break;
        case 21: 
          { ts.add(new Token("Variables tipo Real",yytext()));return symbol(sym.tipoReal);
          }
        case 49: break;
        case 8: 
          { ts.add(new Token("operador logico ", yytext()));return symbol(sym.ol);
          }
        case 50: break;
        case 17: 
          { ts.add(new Token("Entrada de datos ",yytext()));return symbol(sym.leer);
          }
        case 51: break;
        case 3: 
          { ts.add(new Token("Numero ", yytext()));return symbol(sym.num);
          }
        case 52: break;
        case 25: 
          { ts.add(new Token("Variables tipo Entero ",yytext()));return symbol(sym.tipoEntero);
          }
        case 53: break;
        case 15: 
          { ts.add(new Token("Condicion Si ",yytext()));return symbol(sym.si);
          }
        case 54: break;
        case 2: 
          { ts.add(new Token("Identificador ", yytext()));return symbol(sym.id);
          }
        case 55: break;
        case 20: 
          { ts.add(new Token("Acciones por falso ",yytext()));return symbol(sym.sino);
          }
        case 56: break;
        case 14: 
          { ts.add(new Token("Cadena ",yytext()));return symbol(sym.cad);
          }
        case 57: break;
        case 30: 
          { ts.add(new Token("Palabra reservada ", yytext()));return symbol(sym.mientras);
          }
        case 58: break;
        case 28: 
          { ts.add(new Token("salida de datos ",yytext()));return symbol(sym.escri);
          }
        case 59: break;
        case 13: 
          { ts.add(new Token("Variables prueba",yytext()));return symbol(sym.variables);
          }
        case 60: break;
        case 7: 
          { ts.add(new Token("Igual ",yytext()));return symbol(sym.eq);
          }
        case 61: break;
        case 4: 
          { 
          }
        case 62: break;
        case 6: 
          { ts.add(new Token("Coma ", yytext()));return symbol(sym.coma);
          }
        case 63: break;
        case 11: 
          { ts.add(new Token("parentesis izquierdo ",yytext()));return symbol(sym.pi);
          }
        case 64: break;
        default: 
          if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
            zzAtEOF = true;
            zzDoEOF();
              { return new java_cup.runtime.Symbol(sym.EOF); }
          } 
          else {
            zzScanError(ZZ_NO_MATCH);
          }
      }
    }
  }


}
