
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Sat Nov 06 20:25:15 COT 2021
//----------------------------------------------------

package analizadorProyecto;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int para = 28;
  public static final int paso = 31;
  public static final int tipoReal = 25;
  public static final int coma = 5;
  public static final int finpara = 3;
  public static final int mientras = 16;
  public static final int sino = 13;
  public static final int enton = 4;
  public static final int hacer = 18;
  public static final int variables = 2;
  public static final int finsi = 15;
  public static final int or = 22;
  public static final int num = 8;
  public static final int op = 7;
  public static final int tipoEntero = 23;
  public static final int ol = 21;
  public static final int finmien = 17;
  public static final int inicio = 12;
  public static final int p_coma = 24;
  public static final int real = 29;
  public static final int EOF = 0;
  public static final int id = 9;
  public static final int hasta = 30;
  public static final int cad = 6;
  public static final int error = 1;
  public static final int escri = 27;
  public static final int fin = 14;
  public static final int pi = 11;
  public static final int si = 26;
  public static final int leer = 19;
  public static final int eq = 20;
  public static final int pd = 10;
}

