
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Sun Nov 07 00:08:30 COT 2021
//----------------------------------------------------

package analizadorProyecto;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int para = 27;
  public static final int paso = 30;
  public static final int tipoReal = 24;
  public static final int coma = 4;
  public static final int finpara = 2;
  public static final int mientras = 15;
  public static final int sino = 12;
  public static final int enton = 3;
  public static final int hacer = 17;
  public static final int finsi = 14;
  public static final int or = 21;
  public static final int num = 7;
  public static final int op = 6;
  public static final int tipoEntero = 22;
  public static final int ol = 20;
  public static final int inicio = 11;
  public static final int finmien = 16;
  public static final int p_coma = 23;
  public static final int real = 28;
  public static final int EOF = 0;
  public static final int id = 8;
  public static final int hasta = 29;
  public static final int cad = 5;
  public static final int error = 1;
  public static final int escri = 26;
  public static final int fin = 13;
  public static final int pi = 10;
  public static final int si = 25;
  public static final int leer = 18;
  public static final int eq = 19;
  public static final int pd = 9;
}

